events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    gzip_static on;

    server {
        listen 80;
        root /app/www;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
